# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 66bed7dd470a93d9273a39ed2a50f5b8eb6e8a62d43ef73f6e9bef3a6e54f341ad21bbb19557290e02e58bcdd7465b97d5c273d398e624431deffddcfe503f81

test:
  secret_key_base: 11b2d6131948598d8976390948c3c40e3b3e663123d45c1b4b147e379b4235dca0834bdd2c08c05098ad26c7b5a8c3f4ce524ba9911c157684173fdb40cb6f40

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
